### ISSUE TITLE
Unable to make it works 

### ISSUE THREAD

**Issue by onemore-creator** [nuxt-modules/style-resources#232]
Everything is quite straightforward: I am creating a new blank nuxt3 project using ```npx nuxi@latest init```, trying to add nuxt-styled-resources and get this error:

```bash
ERROR  Cannot restart nuxt:  Cannot read properties of undefined (reading 'nuxt') 
at nuxtStyledResources (node_modules/@nuxtjs/style-resources/lib/module.js:7:25) 
at installModule (node_modules/@nuxt/kit/dist/index.mjs:2415:101) 
at async initNuxt (node_modules/nuxt/dist/index.mjs:4233:7)
at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:6879:5)
at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:6811:7)
at async _applyPromised (node_modules/nuxi/dist/chunks/dev2.mjs:3805:10)
```

**Comment by antiden** [comment]
@onemore-creator Use "@nuxtjs/style-resources": "^2",

**Comment by ninanung** [comment]
@onemore-creator Did you make it? im struggling with this module + nuxt3 + vite.

**Comment by DLLluoluo** [comment]
> [@onemore-creator](https://github.com/onemore-creator) Use "@nuxtjs/style-resources": "^2",使用 “@nuxtjs/style-resources”： “^2”，

On npm I only see that the latest version of @nuxtjs/style-resources is 1.2.2, version 2.x has not been released yet

https://www.npmjs.com/package/@nuxtjs/style-resources?activeTab=readme

**Comment by ninanung** [comment]
> > [@onemore-creator](https://github.com/onemore-creator) Use "@nuxtjs/style-resources": "^2",使用 “@nuxtjs/style-resources”： “^2”，
> 
> On npm I only see that the latest version of @nuxtjs/style-resources is 1.2.2, version 2.x has not been released yet
> 
> https://www.npmjs.com/package/@nuxtjs/style-resources?activeTab=readme

Actually 2.0 has been released. Here is v2.0 page https://www.npmjs.com/package/@nuxtjs/style-resources/v/2.0.0
